-- Add more Indian pharmaceutical drugs to the database
INSERT INTO public.drugs (
  name, generic_name, brands, composition, side_effects, dosage_forms, 
  disorders, incompatibility, category, therapeutic_class, pharmacological_class,
  mechanism, indications, contraindications, warnings, dosage, pharmacokinetics,
  drug_interactions, monitoring, pregnancy_category, lactation, overdose, storage,
  available_strengths, is_premium
) VALUES 
('Atorvastatin', 'Atorvastatin', ARRAY['Lipitor', 'Atorva', 'Storvas'],
 '[{"activeIngredient": "Atorvastatin calcium", "strength": "20mg"}]'::jsonb,
 ARRAY['Myalgia', 'Headache', 'GI upset'], ARRAY['Tablet'],
 ARRAY['Hypercholesterolemia', 'CAD'], ARRAY['Grapefruit'],
 'Statin', 'Cardiovascular', 'HMG-CoA reductase inhibitor',
 'Inhibits cholesterol synthesis', ARRAY['Hypercholesterolemia', 'Atherosclerosis'],
 ARRAY['Active liver disease', 'Pregnancy'], ARRAY['Monitor liver enzymes'],
 '{"adult": "10-80mg daily", "pediatric": "Not recommended", "elderly": "10mg daily"}',
 '{"absorption": "Rapid", "distribution": "High protein binding", "metabolism": "Hepatic", "elimination": "Biliary", "halfLife": "14 hours", "bioavailability": "14%"}',
 ARRAY['Warfarin', 'Cyclosporine'], ARRAY['Liver enzymes', 'CK'], 'X', 'Contraindicated',
 'Supportive care', 'Store at room temperature', ARRAY['10mg', '20mg', '40mg', '80mg'], false),

('Azathioprine', 'Azathioprine', ARRAY['Imuran', 'Azoran'],
 '[{"activeIngredient": "Azathioprine", "strength": "50mg"}]'::jsonb,
 ARRAY['Bone marrow suppression', 'Nausea', 'Hepatotoxicity'], ARRAY['Tablet'],
 ARRAY['Autoimmune diseases', 'Organ transplant'], ARRAY['Allopurinol'],
 'Immunosuppressant', 'Immunology', 'Purine analog',
 'Inhibits DNA/RNA synthesis', ARRAY['Rheumatoid arthritis', 'IBD'],
 ARRAY['Pregnancy', 'Live vaccines'], ARRAY['Monitor blood counts'],
 '{"adult": "1-3mg/kg daily", "pediatric": "Based on weight", "elderly": "Reduce dose"}',
 '{"absorption": "Well absorbed", "distribution": "Wide", "metabolism": "Hepatic", "elimination": "Renal", "halfLife": "3-5 hours", "bioavailability": "Good"}',
 ARRAY['Allopurinol', 'ACE inhibitors'], ARRAY['CBC', 'Liver function'], 'D', 'Contraindicated',
 'Supportive care', 'Store at room temperature', ARRAY['25mg', '50mg'], true),

('Amiodarone', 'Amiodarone', ARRAY['Cordarone', 'Amiodar'],
 '[{"activeIngredient": "Amiodarone hydrochloride", "strength": "200mg"}]'::jsonb,
 ARRAY['Pulmonary toxicity', 'Thyroid dysfunction', 'Corneal deposits'], ARRAY['Tablet', 'Injection'],
 ARRAY['Arrhythmias', 'Atrial fibrillation'], ARRAY['Warfarin'],
 'Antiarrhythmic', 'Cardiovascular', 'Class III antiarrhythmic',
 'Blocks multiple ion channels', ARRAY['Ventricular arrhythmias', 'Atrial fibrillation'],
 ARRAY['Pulmonary fibrosis', 'Thyroid disease'], ARRAY['Monitor thyroid, pulmonary function'],
 '{"adult": "200-400mg daily", "pediatric": "Not established", "elderly": "Lower doses"}',
 '{"absorption": "Variable", "distribution": "Large volume", "metabolism": "Hepatic", "elimination": "Biliary", "halfLife": "25-110 days", "bioavailability": "22-86%"}',
 ARRAY['Warfarin', 'Digoxin'], ARRAY['Thyroid function', 'Chest X-ray'], 'D', 'Avoid',
 'Supportive care', 'Protect from light', ARRAY['100mg', '200mg'], true),

('Gabapentin', 'Gabapentin', ARRAY['Neurontin', 'Gabapin'],
 '[{"activeIngredient": "Gabapentin", "strength": "300mg"}]'::jsonb,
 ARRAY['Dizziness', 'Somnolence', 'Ataxia'], ARRAY['Capsule', 'Tablet'],
 ARRAY['Neuropathic pain', 'Epilepsy'], ARRAY['Antacids'],
 'Anticonvulsant', 'Neurology', 'GABA analog',
 'Modulates calcium channels', ARRAY['Neuropathic pain', 'Partial seizures'],
 ARRAY['Renal impairment', 'Depression'], ARRAY['Monitor renal function'],
 '{"adult": "300-3600mg daily", "pediatric": "Based on weight", "elderly": "Reduce dose"}',
 '{"absorption": "Dose dependent", "distribution": "Limited", "metabolism": "None", "elimination": "Renal", "halfLife": "5-7 hours", "bioavailability": "60%"}',
 ARRAY['Antacids', 'Morphine'], ARRAY['Renal function'], 'C', 'Compatible',
 'Supportive care', 'Store at room temperature', ARRAY['100mg', '300mg', '400mg'], false),

('Furosemide', 'Furosemide', ARRAY['Lasix', 'Frusenex'],
 '[{"activeIngredient": "Furosemide", "strength": "40mg"}]'::jsonb,
 ARRAY['Hypokalemia', 'Dehydration', 'Ototoxicity'], ARRAY['Tablet', 'Injection'],
 ARRAY['Edema', 'Heart failure', 'Hypertension'], ARRAY['Lithium'],
 'Diuretic', 'Cardiovascular', 'Loop diuretic',
 'Inhibits sodium-potassium-chloride cotransporter', ARRAY['Edema', 'Hypertension'],
 ARRAY['Anuria', 'Severe electrolyte depletion'], ARRAY['Monitor electrolytes'],
 '{"adult": "20-80mg daily", "pediatric": "1-2mg/kg", "elderly": "Lower doses"}',
 '{"absorption": "Rapid", "distribution": "Protein bound", "metabolism": "Hepatic", "elimination": "Renal", "halfLife": "1-2 hours", "bioavailability": "60-70%"}',
 ARRAY['Lithium', 'Digoxin'], ARRAY['Electrolytes', 'Kidney function'], 'C', 'Compatible',
 'Replace fluids/electrolytes', 'Store at room temperature', ARRAY['20mg', '40mg', '80mg'], false),

('Lisinopril', 'Lisinopril', ARRAY['Prinivil', 'Zestril'],
 '[{"activeIngredient": "Lisinopril", "strength": "10mg"}]'::jsonb,
 ARRAY['Dry cough', 'Hyperkalemia', 'Angioedema'], ARRAY['Tablet'],
 ARRAY['Hypertension', 'Heart failure'], ARRAY['Potassium supplements'],
 'ACE Inhibitor', 'Cardiovascular', 'ACE inhibitor',
 'Inhibits angiotensin-converting enzyme', ARRAY['Hypertension', 'Heart failure'],
 ARRAY['Pregnancy', 'Bilateral renal artery stenosis'], ARRAY['Monitor kidney function'],
 '{"adult": "5-40mg daily", "pediatric": "Based on weight", "elderly": "2.5mg daily"}',
 '{"absorption": "25%", "distribution": "Limited", "metabolism": "None", "elimination": "Renal", "halfLife": "12 hours", "bioavailability": "25%"}',
 ARRAY['Potassium supplements', 'NSAIDs'], ARRAY['Kidney function', 'Electrolytes'], 'D', 'Contraindicated',
 'Supportive care', 'Store at room temperature', ARRAY['2.5mg', '5mg', '10mg', '20mg'], false)