-- Add comprehensive drug data for Indian pharmaceutical market
INSERT INTO public.drugs (
  name, generic_name, brands, composition, side_effects, dosage_forms, 
  disorders, incompatibility, category, therapeutic_class, pharmacological_class,
  mechanism, indications, contraindications, warnings, dosage, pharmacokinetics,
  drug_interactions, monitoring, pregnancy_category, lactation, overdose, storage,
  available_strengths, is_premium
) VALUES 
('Cotiamide', 'Cotrimoxazole', ARRAY['Bactrim', 'Septran'], 
 '[{"activeIngredient": "Sulfamethoxazole", "strength": "400mg"}, {"activeIngredient": "Trimethoprim", "strength": "80mg"}]'::jsonb,
 ARRAY['Nausea', 'Vomiting', 'Diarrhea', 'Rash'], ARRAY['Tablet', 'Suspension'],
 ARRAY['UTI', 'Pneumonia', 'Bronchitis'], ARRAY['Warfarin', 'Methotrexate'],
 'Antibiotics', 'Anti-infective', 'Folate antagonist',
 'Inhibits bacterial folate synthesis', ARRAY['Urinary tract infections', 'Respiratory infections'],
 ARRAY['Allergy to sulfonamides'], ARRAY['Monitor blood counts'], 
 '{"adult": "2 tablets twice daily", "pediatric": "Based on weight", "elderly": "Reduce dose"}',
 '{"absorption": "Well absorbed", "distribution": "Wide", "metabolism": "Hepatic", "elimination": "Renal", "halfLife": "8-12 hours", "bioavailability": "90%"}',
 ARRAY['Warfarin', 'Phenytoin'], ARRAY['CBC', 'Renal function'], 'B', 'Compatible with breastfeeding',
 'Supportive care', 'Store at room temperature', ARRAY['400/80mg'], false),

('Acetylsalicylic Acid', 'Aspirin', ARRAY['Ecosprin', 'Disprin', 'Aspisol'],
 '[{"activeIngredient": "Acetylsalicylic acid", "strength": "75mg"}]'::jsonb,
 ARRAY['GI bleeding', 'Nausea', 'Tinnitus'], ARRAY['Tablet', 'Enteric coated'],
 ARRAY['Cardio protection', 'Pain', 'Fever'], ARRAY['Warfarin', 'Methotrexate'],
 'Antiplatelet', 'Cardiovascular', 'COX inhibitor',
 'Irreversibly inhibits COX enzymes', ARRAY['Cardioprotection', 'Analgesic'],
 ARRAY['Active bleeding', 'Peptic ulcer'], ARRAY['GI bleeding risk'],
 '{"adult": "75-100mg daily", "pediatric": "Not recommended", "elderly": "75mg daily"}',
 '{"absorption": "Rapid", "distribution": "Wide", "metabolism": "Hepatic", "elimination": "Renal", "halfLife": "2-3 hours", "bioavailability": "80-100%"}',
 ARRAY['Warfarin', 'ACE inhibitors'], ARRAY['Bleeding time'], 'D', 'Avoid in breastfeeding',
 'Gastric lavage, supportive care', 'Store in cool, dry place', ARRAY['75mg', '150mg'], false),

('Albendazole', 'Albendazole', ARRAY['Zentel', 'Bandy'],
 '[{"activeIngredient": "Albendazole", "strength": "400mg"}]'::jsonb,
 ARRAY['Nausea', 'Abdominal pain', 'Headache'], ARRAY['Tablet', 'Suspension'],
 ARRAY['Parasitic infections', 'Worm infestations'], ARRAY['Pregnancy'],
 'Anthelmintic', 'Anti-parasitic', 'Benzimidazole',
 'Inhibits tubulin polymerization', ARRAY['Roundworm', 'Hookworm', 'Tapeworm'],
 ARRAY['Pregnancy', 'Liver disease'], ARRAY['Monitor liver function'],
 '{"adult": "400mg single dose", "pediatric": "Based on weight", "elderly": "400mg"}',
 '{"absorption": "Variable", "distribution": "CSF penetration", "metabolism": "Hepatic", "elimination": "Biliary", "halfLife": "8-12 hours", "bioavailability": "Variable"}',
 ARRAY['Cimetidine', 'Corticosteroids'], ARRAY['Liver enzymes'], 'C', 'Contraindicated',
 'Supportive care', 'Store at room temperature', ARRAY['400mg'], false),

('Alfacalcidol', 'Alfacalcidol', ARRAY['Alfacid', 'Calcirol'],
 '[{"activeIngredient": "Alfacalcidol", "strength": "0.25mcg"}]'::jsonb,
 ARRAY['Hypercalcemia', 'Nausea', 'Weakness'], ARRAY['Capsule', 'Solution'],
 ARRAY['Osteoporosis', 'Rickets', 'Hypoparathyroidism'], ARRAY['Thiazides'],
 'Vitamin D analogue', 'Bone metabolism', 'Vitamin D receptor agonist',
 'Increases calcium absorption', ARRAY['Osteoporosis', 'Vitamin D deficiency'],
 ARRAY['Hypercalcemia', 'Kidney stones'], ARRAY['Monitor serum calcium'],
 '{"adult": "0.25-1mcg daily", "pediatric": "Based on weight", "elderly": "Start low"}',
 '{"absorption": "Good", "distribution": "Protein bound", "metabolism": "Hepatic", "elimination": "Biliary", "halfLife": "3-6 hours", "bioavailability": "Good"}',
 ARRAY['Thiazides', 'Digitalis'], ARRAY['Serum calcium', 'Phosphate'], 'A', 'Compatible',
 'Discontinue, IV fluids', 'Protect from light', ARRAY['0.25mcg', '0.5mcg'], false),

('Amlodipine', 'Amlodipine', ARRAY['Amlokind', 'Amlopres', 'Stamlo'],
 '[{"activeIngredient": "Amlodipine besylate", "strength": "5mg"}]'::jsonb,
 ARRAY['Ankle edema', 'Dizziness', 'Fatigue'], ARRAY['Tablet'],
 ARRAY['Hypertension', 'Angina'], ARRAY['Grapefruit juice'],
 'Calcium channel blocker', 'Cardiovascular', 'Dihydropyridine CCB',
 'Blocks L-type calcium channels', ARRAY['Hypertension', 'Angina pectoris'],
 ARRAY['Cardiogenic shock', 'Severe aortic stenosis'], ARRAY['Monitor BP'],
 '{"adult": "5-10mg daily", "pediatric": "Not established", "elderly": "2.5mg daily"}',
 '{"absorption": "Slow", "distribution": "High volume", "metabolism": "Hepatic", "elimination": "Renal", "halfLife": "30-50 hours", "bioavailability": "64-90%"}',
 ARRAY['Simvastatin', 'Cyclosporine'], ARRAY['Blood pressure', 'Heart rate'], 'C', 'Compatible',
 'Supportive care, calcium', 'Store at room temperature', ARRAY['2.5mg', '5mg', '10mg'], false),

('Metformin', 'Metformin', ARRAY['Glycomet', 'Glucophage', 'Obimet'],
 '[{"activeIngredient": "Metformin hydrochloride", "strength": "500mg"}]'::jsonb,
 ARRAY['Nausea', 'Diarrhea', 'Metallic taste'], ARRAY['Tablet', 'Extended release'],
 ARRAY['Type 2 diabetes', 'PCOS'], ARRAY['Contrast agents'],
 'Antidiabetic', 'Endocrine', 'Biguanide',
 'Decreases hepatic glucose production', ARRAY['Type 2 diabetes mellitus'],
 ARRAY['Renal impairment', 'Lactic acidosis'], ARRAY['Monitor renal function'],
 '{"adult": "500mg twice daily", "pediatric": "Not recommended", "elderly": "Reduce dose"}',
 '{"absorption": "50-60%", "distribution": "Limited", "metabolism": "None", "elimination": "Renal", "halfLife": "4-9 hours", "bioavailability": "50-60%"}',
 ARRAY['Contrast media', 'Alcohol'], ARRAY['Renal function', 'Lactate'], 'B', 'Compatible',
 'Discontinue, treat acidosis', 'Store at room temperature', ARRAY['500mg', '850mg', '1000mg'], false),

('Atorvastatin', 'Atorvastatin', ARRAY['Lipitor', 'Atorva', 'Storvas'],
 '[{"activeIngredient": "Atorvastatin calcium", "strength": "20mg"}]'::jsonb,
 ARRAY['Myalgia', 'Headache', 'GI upset'], ARRAY['Tablet'],
 ARRAY['Hypercholesterolemia', 'CAD'], ARRAY['Grapefruit'],
 'Statin', 'Cardiovascular', 'HMG-CoA reductase inhibitor',
 'Inhibits cholesterol synthesis', ARRAY['Hypercholesterolemia', 'Atherosclerosis'],
 ARRAY['Active liver disease', 'Pregnancy'], ARRAY['Monitor liver enzymes'],
 '{"adult": "10-80mg daily", "pediatric": "Not recommended", "elderly": "10mg daily"}',
 '{"absorption": "Rapid", "distribution": "High protein binding", "metabolism": "Hepatic", "elimination": "Biliary", "halfLife": "14 hours", "bioavailability": "14%"}',
 ARRAY['Warfarin', 'Cyclosporine'], ARRAY['Liver enzymes', 'CK'], 'X', 'Contraindicated',
 'Supportive care', 'Store at room temperature', ARRAY['10mg', '20mg', '40mg', '80mg'], false),

('Amoxicillin', 'Amoxicillin', ARRAY['Amoxil', 'Augmentin', 'Clavam'],
 '[{"activeIngredient": "Amoxicillin trihydrate", "strength": "500mg"}]'::jsonb,
 ARRAY['Diarrhea', 'Nausea', 'Rash'], ARRAY['Capsule', 'Suspension', 'Injection'],
 ARRAY['Bacterial infections', 'UTI', 'Pneumonia'], ARRAY['Allopurinol'],
 'Antibiotic', 'Anti-infective', 'Beta-lactam',
 'Inhibits cell wall synthesis', ARRAY['Bacterial infections', 'Otitis media'],
 ARRAY['Penicillin allergy', 'Mononucleosis'], ARRAY['Monitor for superinfection'],
 '{"adult": "500mg three times daily", "pediatric": "Based on weight", "elderly": "500mg TID"}',
 '{"absorption": "Well absorbed", "distribution": "Wide", "metabolism": "Minimal", "elimination": "Renal", "halfLife": "1-1.3 hours", "bioavailability": "74-92%"}',
 ARRAY['Warfarin', 'Oral contraceptives'], ARRAY['Signs of superinfection'], 'B', 'Compatible',
 'Supportive care', 'Store at room temperature', ARRAY['250mg', '500mg'], false)