// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxcxqjubctslypthviux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94Y3hxanViY3RzbHlwdGh2aXV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDI3NDgsImV4cCI6MjA3MjYxODc0OH0.qiY3MAy0TxD610ORcJ-r6cC8xewUB830dMqMjMIBqDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});