// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uduhhtaxrodotrdrztp n.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkdWhodGF4cm9kb3RyZHJ6dHBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMTc1NjMsImV4cCI6MjA3ODY5MzU2M30.Ju3XzOxCSVc_raNA4CEywfdT0DO3dlAnjNeodvWz3jQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});