// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhagpaqksijwitsbqsgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoYWdwYXFrc2lqd2l0c2Jxc2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMTA3MTgsImV4cCI6MjA3MDU4NjcxOH0.XcFlb6CEatKHhbaxCijZ_nR_zmCs3rmsNxYDraeemIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});